$(window).load(function(){
	$('.blogEntryButt').click(function(){
		$('#blogWrapper').show(); 
		$('#headLineContaner').hide(); 
    });
	$('.headlineEntryButt').click(function(){
		$('#headLineContaner').show(); 
		$('#blogWrapper').hide(); 
    });
});